-- MySQL Script generated by MySQL Workbench
-- Fri May 27 14:20:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Мини-гостиница
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Мини-гостиница
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Мини-гостиница` DEFAULT CHARACTER SET utf8 ;
USE `Мини-гостиница` ;

-- -----------------------------------------------------
-- Table `Мини-гостиница`.`room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Мини-гостиница`.`room_type` (
  `id_room_type` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  `amount` INT NULL,
  `cost_per_day` DECIMAL(8,2),
  `amount_2beds` INT NULL,
  `amount_1beds` INT NULL,
  PRIMARY KEY (`id_room_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Мини-гостиница`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Мини-гостиница`.`room` (
  `id_room` INT NOT NULL AUTO_INCREMENT,
  `id_room_type` INT NOT NULL,
  `number_room` INT NULL,
  `floor` INT NULL,
  `roomcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_room`),
  INDEX `id_room_type_idx` (`id_room_type` ASC) VISIBLE,
  CONSTRAINT `id_room_type_lol`
    FOREIGN KEY (`id_room_type`)
    REFERENCES `Мини-гостиница`.`room_type` (`id_room_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Мини-гостиница`.`amenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Мини-гостиница`.`amenities` (
  `id_amenities` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_amenities`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Мини-гостиница`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Мини-гостиница`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(50) NULL,
  `contact_details` VARCHAR(45) NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Мини-гостиница`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Мини-гостиница`.`account` (
  `id_account` INT NOT NULL auto_increment,
  `sum_price_services` DECIMAL(8,2) NULL,
  `paid_services` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id_account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Мини-гостиница`.`reserving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Мини-гостиница`.`reserving` (
  `id_reserving` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  `id_room` INT NOT NULL,
  `date_reserving` TIMESTAMP NULL,
  `cost` DECIMAL(8,2) NULL,
  `paid_cost` DECIMAL(8,2) NULL,
  `id_account` INT NULL,
  `type_payment` VARCHAR(45) NULL,
  `status_payment_reserving` VARCHAR(45) NOT NULL,
  `date_departure` TIMESTAMP NULL,
  `amount_days` INT NULL,
  PRIMARY KEY (`id_reserving`),
  INDEX `id_room_idx` (`id_room` ASC) VISIBLE,
  INDEX `id_client_idx` (`id_client` ASC) VISIBLE,
  INDEX `id_account_idx` (`id_account` ASC) VISIBLE,
  CONSTRAINT `id_room`
    FOREIGN KEY (`id_room`)
    REFERENCES `Мини-гостиница`.`room` (`id_room`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `Мини-гостиница`.`client` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_account_lol`
    FOREIGN KEY (`id_account`)
    REFERENCES `Мини-гостиница`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Мини-гостиница`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Мини-гостиница`.`services` (
  `id_services` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL(8,2) NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id_services`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Мини-гостиница`.`room_amenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Мини-гостиница`.`room_amenities` (
  `id_amenities` INT NOT NULL,
  `id_room_type` INT NOT NULL,
  `amount` INT NULL,
  INDEX `id_room_type_idx` (`id_amenities` ASC) VISIBLE,
  INDEX `id_room_type_idx1` (`id_room_type` ASC) VISIBLE,
  CONSTRAINT `id_amenities`
    FOREIGN KEY (`id_amenities`)
    REFERENCES `Мини-гостиница`.`amenities` (`id_amenities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_room_type_kek`
    FOREIGN KEY (`id_room_type`)
    REFERENCES `Мини-гостиница`.`room_type` (`id_room_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Мини-гостиница`.`complete_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Мини-гостиница`.`complete_services` (
  `id_complete_services` INT NOT NULL auto_increment,
  `id_services` INT NOT NULL,
  `date` TIMESTAMP NULL,
  `comment` VARCHAR(100) NULL,
  `price` DECIMAL(8,2) NULL,
  `id_account` INT NULL,
  PRIMARY KEY (`id_complete_services`),
  INDEX `id_services_idx` (`id_services` ASC) VISIBLE,
  INDEX `id_account_idx` (`id_account` ASC) VISIBLE,
  CONSTRAINT `id_services`
    FOREIGN KEY (`id_services`)
    REFERENCES `Мини-гостиница`.`services` (`id_services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_account_kek`
    FOREIGN KEY (`id_account`)
    REFERENCES `Мини-гостиница`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
